---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - tests.tbd.com
  resources:
  - loadtests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tests.tbd.com
  resources:
  - loadtests/finalizers
  verbs:
  - update
- apiGroups:
  - tests.tbd.com
  resources:
  - loadtests/status
  verbs:
  - get
  - patch
  - update
