apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: loadtests.tests.tbd.com
spec:
  group: tests.tbd.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                method:
                  type: string
                  enum: ["GET", "POST"]
                address:
                  type: string
                duration:
                  type: string
            status:
              type: object
              properties:
                requests:
                  type: integer
  scope: Namespaced
  names:
    plural: loadtests
    singular: loadtest
    kind: LoadTest
    shortNames:
    - lt
    categories:
    - tests
